import {
  Calendar,
  Cancel,
  Checkmark,
  Down,
  Edit,
  Eye,
  Fullscreen,
  HeartFilled,
  HeartOutlined,
  Left,
  Location,
  LogoMumble,
  Logout,
  MumbleGradient,
  MumbleText,
  Mumble,
  Profile,
  ReplyFilled,
  ReplyOutlined,
  Repost,
  Right,
  Send,
  Settings,
  Share,
  Time,
  Up,
  Upload,
} from './icons';

export const Icons = {
  calendar: <Calendar />,
  cancel: <Cancel />,
  checkmark: <Checkmark />,
  down: <Down />,
  edit: <Edit />,
  eye: <Eye />,
  fullscreen: <Fullscreen />,
  'heart-filled': <HeartFilled />,
  'heart-outlined': <HeartOutlined />,
  left: <Left />,
  location: <Location />,
  'logo-mumble': <LogoMumble className={'fill-violet-600'} />,
  logout: <Logout />,
  'mumble-gradient': <MumbleGradient />,
  'mumble-text': <MumbleText className={'fill-violet-600'} />,
  mumble: <Mumble />,
  profile: <Profile />,
  'reply-filled': <ReplyFilled />,
  'reply-outlined': <ReplyOutlined />,
  repost: <Repost />,
  right: <Right />,
  send: <Send />,
  settings: <Settings />,
  share: <Share />,
  time: <Time />,
  up: <Up />,
  upload: <Upload />,
};

export const LikeRepostIcons = {
  HeartFilled: <HeartFilled />,
  ReplyFilled: <ReplyFilled />,
};

export type IconTypes = keyof typeof Icons;
