import {
  Calendar,
  Cancel,
  Checkmark,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Edit,
  Eye,
  Fullscreen,
  HeartFilled,
  HeartOutlined,
  Location,
  Logout,
  Mumble,
  MumbleText,
  LogoMumble,
  Profile,
  ReplyFilled,
  ReplyOutlined,
  Repost,
  Send,
  Settings,
  Share,
  Time,
  Upload,
} from './icons';

export const Icons = {
  joined: <Calendar />,
  cancel: <Cancel />,
  checkmark: <Checkmark />,
  chevronUp: <ChevronUp />,
  chevronDown: <ChevronDown />,
  chevronLeft: <ChevronLeft />,
  chevronRight: <ChevronRight />,
  edit: <Edit />,
  eye: <Eye />,
  fullscreen: <Fullscreen />,
  heartFilled: <HeartFilled />,
  heartOutlined: <HeartOutlined />,
  location: <Location />,
  logout: <Logout />,
  mumble: <Mumble />,
  logoMumble: <LogoMumble className={'fill-violet-600'} />,
  mumbleText: <MumbleText className={'fill-violet-600'} />,
  username: <Profile />,
  replyFilled: <ReplyFilled />,
  replyOutlined: <ReplyOutlined />,
  repost: <Repost />,
  send: <Send />,
  settings: <Settings />,
  share: <Share />,
  timestamp: <Time />,
  upload: <Upload />,
};

export const LikeRepostIcons = {
  HeartFilled: <HeartFilled />,
  ReplyFilled: <ReplyFilled />,
};
