name: Release Component Library

on:
  push:
    branches:
      - master

concurrency:
  group: 'release'
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and Deploy Component Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm i
      - run: npm run build
      - name: semantic release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
