name: Deploy Storybook

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Build storybook static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
      - name: Setup yarn
      - run: yarn set version berry
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
          cache: yarn
      - run: yarn install
      - run: yarn build-storybook
      - uses: actions/upload-pages-artifact@v1
        with:
          path: packages/design-system-component-library-yeahyeahyeah/storybook-static

  deploy:
    environment:
      name: Storybook
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy storybook to pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
